# Generated by Django 4.2.8 on 2024-04-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-updated'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
